# Generated by Django 3.2.6 on 2025-05-26 04:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='Identificador del paciente (puede ser UUID o cadena)', max_length=36)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se asignó el paciente al médico')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='personal_medico.doctor')),
            ],
            options={
                'verbose_name': 'Asignación de paciente',
                'verbose_name_plural': 'Asignaciones de pacientes',
                'db_table': 'patient_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_at'], name='patient_ass_assigne_10038e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['doctor', 'assigned_at'], name='patient_ass_doctor__b06584_idx'),
        ),
    ]
